import LogoutBtn from "@/components/logout-btn";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className='flex-1 flex flex-col items-center gap-4 p-4 pt-0 sm:p-8 sm:pt-0 overflow-y-auto sm:pb-2'>
			<div className='flex'>
				<LogoutBtn />
			</div>
			{children}
		</main>
	);
}
