import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import UserForm from "@/components/user-form";
import githubOctacat from "../../public/github-octacat.png";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='flex h-screen flex-col items-center gap-5 sm:gap-8 p-4 sm:p-8'>
					<Image
						src={githubOctacat}
						alt='Github Logo'
						height={80}
						width={80}
						placeholder='blur'
					/>
					<Suspense>
						<UserForm />
					</Suspense>
					{children}
				</main>
			</body>
		</html>
	);
}
