import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import githubOctacat from "../../public/github-octacat.png";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='flex h-screen flex-col items-center gap-4 p-4 sm:p-8'>
					<Image
						src={githubOctacat}
						alt='Github Logo'
						height={80}
						width={80}
						placeholder='blur'
					/>
					<div className='text-center'>
						<h1
							className='text-xl sm:text-4xl font-black glitch'
							data-text='Git Mates !'
						>
							Git Mates !
						</h1>
						<p className='animate-typing max-w-fit overflow-hidden whitespace-nowrap sm:text-lg  pr-0.5  text-white font-bold leading-none my-1'>
							Discover your true gitizens.
						</p>
					</div>
					{children}
				</main>
			</body>
		</html>
	);
}
